get_fake_response = [
    {
        "id": "d62e1c56-2ae3-4df6-86bc-631996df59a3",
        "type": "Full Time",
        "url": "https://jobs.github.com/positions/d62e1c56-2ae3-4df6-86bc-631996df59a3",
        "created_at": "Fri May 07 16:38:13 UTC 2021",
        "company": "Walmart",
        "company_url": "http:",
        "location": "SUNNYVALE, CA",
        "title": "Principal Software Engineer",
        "description": "some-random-description",
        "how_to_apply": "some-random-guidance-on-how-to-apply",
        "company_logo": "some-random-logo",
    },
    {
        "id": "41b48824-9447-43c6-8505-c17d88b16c34",
        "type": "Full Time",
        "url": "https://jobs.github.com/positions/41b48824-9447-43c6-8505-c17d88b16c34",
        "created_at": "Fri May 07 16:29:26 UTC 2021",
        "company": "Walmart",
        "company_url": "http:",
        "location": "SUNNYVALE, CA",
        "title": "Senior Data Scientist",
        "description": "some-random-description",
        "how_to_apply": "some-random-guidance-on-how-to-apply",
        "company_logo": "some-random-logo",
    },
    {
        "id": "d689eebb-1751-4605-be8b-406e292a06d7",
        "type": "Full Time",
        "url": "https://jobs.github.com/positions/d689eebb-1751-4605-be8b-406e292a06d7",
        "created_at": "Fri May 07 16:26:30 UTC 2021",
        "company": "Walmart",
        "company_url": "http:",
        "location": "SUNNYVALE, CA",
        "title": "Software Engineer",
        "description": "some-random-description",
        "how_to_apply": "some-random-guidance-on-how-to-apply",
        "company_logo": "some-random-logo",
    },
    {
        "id": "ec39177c-a66d-4ec4-b5ff-d20d60b6c8f6",
        "type": "Full Time",
        "url": "https://jobs.github.com/positions/ec39177c-a66d-4ec4-b5ff-d20d60b6c8f6",
        "created_at": "Fri May 07 16:24:10 UTC 2021",
        "company": "Walmart",
        "company_url": "http:",
        "location": "SUNNYVALE, CA",
        "title": "Principal Data Scientist - Search",
        "description": "some-random-description",
        "how_to_apply": "some-random-guidance-on-how-to-apply",
        "company_logo": "some-random-logo",
    },
    {
        "id": "2b0ec8b1-d91c-4f77-b938-1a816ba02a4b",
        "type": "Full Time",
        "url": "https://jobs.github.com/positions/2b0ec8b1-d91c-4f77-b938-1a816ba02a4b",
        "created_at": "Fri May 07 16:11:48 UTC 2021",
        "company": "Walmart",
        "company_url": "http:",
        "location": "SUNNYVALE, CA",
        "title": "Staff Software Engineer – Supply Chain",
        "description": "some-random-description",
        "how_to_apply": "some-random-guidance-on-how-to-apply",
        "company_logo": None,
    },
]

get_wrong_location = {
    "detail": "'san franciso' is not one of ['chicago', 'san francisco', 'phoenix', 'london', 'beijing', 'paris']\n\nFailed validating 'enum' in schema:\n    {'enum': ['chicago',\n              'san francisco',\n              'phoenix',\n              'london',\n              'beijing',\n              'paris'],\n     'type': 'string'}\n\nOn instance:\n    'san franciso'",
    "status": 400,
    "title": "Bad Request",
    "type": "about:blank",
}

get_wrong_language = {
    "detail": "'pythona' is not one of ['javascript', 'java', 'python', 'react', 'ruby', 'go']\n\nFailed validating 'enum' in schema:\n    {'enum': ['javascript', 'java', 'python', 'react', 'ruby', 'go'],\n     'type': 'string'}\n\nOn instance:\n    'pythona'",
    "status": 400,
    "title": "Bad Request",
    "type": "about:blank",
}
